server:
  port: 8080

spring:
  datasource:
    username: root
    password: abcd-1234
    url: jdbc:mysql://192.168.1.153:3306/db_huawei?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # 连接密码
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    # 连接超时时间（毫秒）
    timeout: 1000

mybatis:
  type-aliases-package: org.huawei.game.model
  mapper-locations: classpath:mapper/*.xml

#showSql
logging:
  level:
    org:
      huawei:
        game: debug


#swagger 配置
#swagger:
#  title: API示例
#  desc: 基于springBoot编写的RESful-API
#  version: 1.0.0
#  termsOfServiceUrl: javascript:void(0)
#  license: Apache 2.0
#  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
#  basePackage: org.huawei.game.controller
#  groupName: 默认API示例分组
#  contactName: wendell
#  contactUrl: https://github.com/wendell-dev/restful-api-demo.git
#  contactEmail: 727169395@qq.com


